<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class BlockAi
{
    // https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/refs/heads/main/robots.txt
    // https://github.com/ai-robots-txt/ai.robots.txt
    // https://robotstxt.com/ai
    protected array $aiUserAgents = [
        'AddSearchBot',
        'AgentDataBot',
        'AgentTimes',
        'AI2Bot',
        'AI2Bot-DeepResearchEval',
        'Ai2Bot-Dolma',
        'aiHitBot',
        'AIWebIndex',
        'amazon-kendra',
        'amazon-QBusiness',
        'Amazonbot',
        'AmazonBuyForMe',
        'Amzn-SearchBot',
        'Amzn-User',
        'Andibot',
        'Anomura',
        'anthropic-ai',
        'ApifyBot',
        'ApifyWebsiteContentCrawler',
        'Applebot',
        'Applebot-Extended',
        'Aranet-SearchBot',
        'atlassian-bot',
        'Awario',
        'AzureAI-SearchBot',
        'bedrockbot',
        'bigsur.ai',
        'BixelBot',
        'Bravebot',
        'Brightbot',
        'Brightbot 1.0',
        'BuddyBot',
        'Bytespider',
        'CCBot',
        'Channel3Bot',
        'ChatGLM-Spider',
        'ChatGPT Agent',
        'ChatGPT-User',
        'Claude-Code',
        'Claude-SearchBot',
        'Claude-User',
        'Claude-Web',
        'ClaudeBot',
        'Cloudflare-AutoRAG',
        'CloudflareBrowserRenderingCrawler',
        'CloudVertexBot',
        ' Code/',
        'cohere-ai',
        'cohere-training-data-crawler',
        'Cotoyogi',
        'CragCrawler',
        'Crawl4AI',
        'Crawlspace',
        'Cursor',
        'Datenbank Crawler',
        'DeepSeekBot',
        'Devin',
        'Diffbot',
        'Diffbot-User',
        'DoubaoBot',
        'DuckAssistBot',
        'Echobot Bot',
        'EchoboxBot',
        'ERNIEBot',
        'ExaBot',
        'ExaSearchBot',
        'FacebookBot',
        'facebookexternalhit',
        'Factset_spyderbot',
        'FirecrawlAgent',
        'FriendlyCrawler',
        'GeistHaus-PageFetcher',
        'Gemini-Deep-Research',
        'Google-Agent',
        'Google-CloudVertexBot',
        'Google-Extended',
        'Google-Firebase',
        'Google-Gemini-CLI',
        'Google-NotebookLM',
        'GoogleAgent-Mariner',
        'GoogleAgent-URLContext',
        'GoogleOther',
        'GoogleOther-Image',
        'GoogleOther-Video',
        'GPTBot',
        'HenkBot',
        'iAskBot',
        'iaskspider',
        'iaskspider/2.0',
        'ICC-Crawler',
        'ImagesiftBot',
        'imageSpider',
        'img2dataset',
        'IntelFeed-People',
        'ISSCyberRiskCrawler',
        'kagi-fetcher',
        'Kangaroo Bot',
        'KeenableBot',
        'Kimi-Agent',
        'Kimi-SearchBot',
        'Kimi-User',
        'KimiBot',
        'KlaviyoAIBot',
        'KunatoCrawler',
        'laion-huggingface-processor',
        'LAIONDownloader',
        'LCC (',
        'Lightpanda',
        'LinerBot',
        'Linguee Bot',
        'LinkupBot',
        'Manus-User',
        'meta-externalagent',
        'Meta-ExternalAgent',
        'meta-externalfetcher',
        'Meta-ExternalFetcher',
        'meta-webindexer',
        'MistralAI-Index',
        'MistralAI-Training',
        'MistralAI-User',
        'MistralAI-User/1.0',
        'Mozilla-Tabstack',
        'MyCentralAIScraperBot',
        'NagetBot',
        'netEstate Imprint Crawler',
        'newsai',
        'NotebookLM',
        'NovaAct',
        'OAI-AdsBot',
        'OAI-SearchBot',
        'omgili',
        'omgilibot',
        'OpenAI',
        'opencode',
        ' Operator/',
        'PanguBot',
        'Panscient',
        'panscient.com',
        'Perplexity-User',
        'PerplexityBot',
        'PetalBot',
        'PhindBot',
        'Poggio-Citations',
        'Poseidon Research Crawler',
        'qodercli',
        'QualifiedBot',
        'Querit-SearchBot',
        'QueritBot',
        'QuillBot',
        'quillbot.com',
        'QwenBot',
        'Reflectionbot',
        'SBIntuitionsBot',
        'Scrapy',
        'SemrushBot-OCOB',
        'SemrushBot-SWA',
        'Shap-User',
        'ShapBot',
        'Sidetrade indexer bot',
        ' Spider/',
        'TavilyBot',
        'Terra Cotta',
        'TerraCotta',
        'Thinkbot',
        'TikTokSpider',
        'Timpibot',
        'TongyiBot',
        'Trae',
        'TwinAgent',
        'UseAI',
        'VelenPublicWebCrawler',
        'WARDBot',
        'Webzio-Extended',
        'webzio-extended',
        'wpbot',
        'WRTNBot',
        ' yak ',
        'YandexAdditional',
        'YandexAdditionalBot',
        'YiyanBot',
        'YouBot',
        'ZanistaBot',
        //
        'TurnitinBot',
        'DataForSeoBot',
        'AwarioBot',
        'AwarioSmartBot',
        'AwarioRssBot',
        'Sentibot',
        'Meltwater',
        'Seekr',
        'peer39_crawler',
        'SemrushBot-FT',
        'SemrushBot-ESI',
    ];

    public function handle(Request $request, Closure $next): Response
    {
        $userAgent = $request->header('User-Agent');

        if ($userAgent) {
            foreach ($this->aiUserAgents as $str) {
                if (stripos($userAgent, $str) !== false) return response('403 Forbidden', 403);
            }
        }

        return $next($request);
    }
}
